/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Business.Donor.Donor;
import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Organization.OrganizationDirectory;

/**
 *
 * @author dabho
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageemployeeJPanel
     */
    private JPanel userprocessContainer;
    private Ecosystem system;
    private OrganizationDirectory organizationDirectory;
    

    public ManageEmployeeJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userprocessContainer=userProcessContainer;
        this.organizationDirectory=organizationDirectory;
        populateOrganizationcmb();
        populateOrganizationEMPcmb();
    }


   public void populateOrganizationcmb()
    {
        organizationJComboBox.removeAllItems();
        
        for(Organization o : organizationDirectory.getOrganizationList())
        {
            organizationJComboBox.addItem(o);
        }
        
        
    }
    public void populateOrganizationEMPcmb()
    {
        organizationEmpJComboBox.removeAllItems();
        
        for(Organization o : organizationDirectory.getOrganizationList())
        {
            organizationEmpJComboBox.addItem(o);
        }
        
        
    }
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)managEmployeeJTable.getModel();
        dtm.setRowCount(0);
        Organization o = (Organization)organizationJComboBox.getSelectedItem();
        if(o != null)
        {
        for(Employee e : o.getEmployeeDirectory().getEmployeeList())
        {
            Object row[] = new Object[2];
            row[0] = e.getId();
            row[1] = e.getName();
            dtm.addRow(row);
        }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        managEmployeeJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        employeenameJLabel = new javax.swing.JLabel();
        employeeJTextField = new javax.swing.JTextField();
        BackJButton1 = new javax.swing.JButton();
        createJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        organizationEmpJComboBox = new javax.swing.JComboBox();

        BackJButton.setText("Back");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managEmployeeJTable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        managEmployeeJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(managEmployeeJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 841, 224));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Manage Employee");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 13, 202, -1));

        employeenameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        employeenameJLabel.setText("Employee Name :");
        add(employeenameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 130, 22));
        add(employeeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 472, 230, 30));

        BackJButton1.setText("Back");
        BackJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButton1ActionPerformed(evt);
            }
        });
        add(BackJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 104, -1));

        createJButton.setText("Create Employee");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 557, 140, -1));

        jLabel1.setText("Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, -1));

        jLabel3.setText("Organization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        organizationEmpJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationEmpJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationEmpJComboBoxActionPerformed(evt);
            }
        });
        add(organizationEmpJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 422, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        populateTable();
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    private void organizationEmpJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationEmpJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationEmpJComboBoxActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        
        Organization o = (Organization)organizationEmpJComboBox.getSelectedItem();
           populateTable();
           
       
        if(employeeJTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter employee name","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Employee e = o.getEmployeeDirectory().createEmployee(employeeJTextField.getText().trim());
           JOptionPane.showMessageDialog(null,"Employee added successfully","Success",1);
           populateTable();
        
     
    }//GEN-LAST:event_createJButtonActionPerformed

    private void BackJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButton1ActionPerformed
        // TODO add your handling code here:
        
        userprocessContainer.remove(this);
        CardLayout layout = (CardLayout) userprocessContainer.getLayout();
        layout.previous(userprocessContainer);
    }//GEN-LAST:event_BackJButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JButton BackJButton1;
    private javax.swing.JButton createJButton;
    private javax.swing.JTextField employeeJTextField;
    private javax.swing.JLabel employeenameJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable managEmployeeJTable;
    private javax.swing.JComboBox organizationEmpJComboBox;
    private javax.swing.JComboBox organizationJComboBox;
    // End of variables declaration//GEN-END:variables
}
