/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Donor;

import Business.Donor.Donor;
import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Role.DonorRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Janhavi
 */
public class AddDonorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDonorJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;



    public AddDonorJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        organisationJLabel = new javax.swing.JLabel();
        locationJLabel = new javax.swing.JLabel();
        passwordJLabel5 = new javax.swing.JLabel();
        organisationNameJTextField = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        locationJLabel1 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        locationJLabel2 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        locationJLabel3 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        locationJLabel4 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        passwordJPasswordField = new javax.swing.JPasswordField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameJLabel.setText("Add Donor");
        jPanel1.add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        organisationJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        organisationJLabel.setText("Organisation Name :");
        jPanel1.add(organisationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 30));

        locationJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel.setText("Address line 1 : ");
        jPanel1.add(locationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        passwordJLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordJLabel5.setText("Password :");
        jPanel1.add(passwordJLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 160, 30));
        jPanel1.add(organisationNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 220, -1));
        jPanel1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 220, -1));

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 120, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 120, 30));

        locationJLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel1.setText("Address line 2 :");
        jPanel1.add(locationJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 30));
        jPanel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 220, -1));

        locationJLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel2.setText("City : ");
        jPanel1.add(locationJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 30));
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 220, -1));

        locationJLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel3.setText("State : ");
        jPanel1.add(locationJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 30));

        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        jPanel1.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 220, -1));

        locationJLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel4.setText("Country : ");
        jPanel1.add(locationJLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, 30));
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 220, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Username :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        jPanel1.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 220, -1));
        jPanel1.add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        
        String userName = userNameJTextField.getText();
        String donorName = organisationNameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String location= a1.getText()+", "+a2.getText()+", "+city.getText()+", "+state.getText()+", "+country.getText();
        if(donorName.matches("[a-zA-Z]+")
                && userName.matches("[a-zA-Z]+"))
                {
        Organization org=null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
             if (organization instanceof DonorOrganization){
                org = organization;
                break;
            }
        }
        if(donorName.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter Donor name","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        Donor d = org.getEmployeeDirectory().createDonor(donorName.trim());
         d.setLocation(location);

        
        org.getUserAccountDirectory().createDonorAccount(userName, password, d, new DonorRole());
        JOptionPane.showMessageDialog(null,"Donor Created","Success",1);

         }
        else {
            JOptionPane.showMessageDialog(null, "Error in adding Donor", "Information", JOptionPane.INFORMATION_MESSAGE);

        }
          
/*

        Network network = system.createAndAddNetwork();
        network.setName("Donor");

        Enterprise.EnterpriseType type = Enterprise.EnterpriseType.Donor;

        String enterpriseName = organisationNameJTextField.getText();

        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(enterpriseName, type);

        String username = userNameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());

        Employee employee = enterprise.getEmployeeDirectory().createEmployee("Donor");
        d.setName(enterpriseName);
        
        

        UserAccount account = enterprise.getUserAccountDirectory().createDonorAccount(username, password, d, new DonorRole());

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sawajp = (SystemAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
*/
        userNameJTextField.setText("");
        userNameJTextField.setText("");
        userNameJTextField.setText("");
        userNameJTextField.setText("");
        userNameJTextField.setText("");
        userNameJTextField.setText("");
    }//GEN-LAST:event_createJButtonActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField city;
    private javax.swing.JTextField country;
    private javax.swing.JButton createJButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel locationJLabel;
    private javax.swing.JLabel locationJLabel1;
    private javax.swing.JLabel locationJLabel2;
    private javax.swing.JLabel locationJLabel3;
    private javax.swing.JLabel locationJLabel4;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel organisationJLabel;
    private javax.swing.JTextField organisationNameJTextField;
    private javax.swing.JLabel passwordJLabel5;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JTextField state;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
