/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Donor;

import Business.Donor.Donor;
import Business.Employee.Employee;
import Business.Product.Product;
import Business.Product.ProductDefination;
import Business.Product.ProductDefinationList;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.ManageDonationsJPanel;

/**
 *
 * @author Janhavi
 */
public class AddProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddProductJPanel
     */

    private JPanel userProcessContainer;
    private ProductDefinationList productDefinationList;
    private Donor donor;

    public AddProductJPanel(JPanel userProcessContainer, ProductDefinationList productDefinationList, Donor donor) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.productDefinationList=productDefinationList;
        this.donor=donor;
        donorComboBox();
    }
    public void donorComboBox(){
        donarJComboBox.removeAllItems();
        for(ProductDefination p : productDefinationList.getProductDefinationList()){

            donarJComboBox.addItem(p);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quantityJLabel = new javax.swing.JLabel();
        quantityJTextField = new javax.swing.JTextField();
        productNameJLabel = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        donarJComboBox = new javax.swing.JComboBox();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Add Donation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 142, 54));

        quantityJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        quantityJLabel.setText("Quantity:");
        jPanel1.add(quantityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 142, 33));

        quantityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityJTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(quantityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 186, 33));

        productNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        productNameJLabel.setText("Product Name:");
        jPanel1.add(productNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 142, 33));

        addJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 98, 43));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 98, 37));

        donarJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donarJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(donarJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        ProductDefination productDefination = (ProductDefination) donarJComboBox.getSelectedItem();
        String quan= quantityJTextField.getText();
        if(quan.matches("[0-9]+"))
        {
        Product p = donor.addProduct();
        p.setName(productDefination.getProductName());
        p.setQuantity(Integer.parseInt(quan));
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Input an integer value", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDonationsJPanel manageDonationsJPanel = (ManageDonationsJPanel) component;
        manageDonationsJPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void donarJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donarJComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_donarJComboBoxActionPerformed

    private void quantityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox donarJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productNameJLabel;
    private javax.swing.JLabel quantityJLabel;
    private javax.swing.JTextField quantityJTextField;
    // End of variables declaration//GEN-END:variables
}
