/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Donor;

import Business.Product.Product;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import userInterface.ManageDonationsJPanel;
/**
 *
 * @author Janhavi
 */
public class UpdateManageDonationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateManageDonationJPanel
     */
    private JPanel userProcessContainer;
    private Product p;
    public UpdateManageDonationJPanel(JPanel userProcessContainer, Product p) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.p = p;
        productnameJTextField.setText(p.getName());
        quantityJTextField.setText(String.valueOf(p.getQuantity()));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productnameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        quantityJLabel = new javax.swing.JLabel();
        quantityJTextField = new javax.swing.JTextField();
        productNameJLabel = new javax.swing.JLabel();
        updateJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productnameJTextField.setEnabled(false);
        jPanel1.add(productnameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 186, 33));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Update Donation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 142, 54));

        quantityJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        quantityJLabel.setText("Quantity:");
        jPanel1.add(quantityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 142, 33));
        jPanel1.add(quantityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 186, 33));

        productNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        productNameJLabel.setText("Product Name:");
        jPanel1.add(productNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 142, 33));

        updateJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 98, 43));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 98, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        p.setQuantity(Integer.parseInt(quantityJTextField.getText()));
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backJButtonActionPerformed
 private void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDonationsJPanel manageDonationsJPanel = (ManageDonationsJPanel) component;
        manageDonationsJPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productNameJLabel;
    private javax.swing.JTextField productnameJTextField;
    private javax.swing.JLabel quantityJLabel;
    private javax.swing.JTextField quantityJTextField;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
