/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Receiver;

import Business.Donor.Donor;
import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Organization.ReceiverOrganization;
import Business.Receiver.Receiver;
import Business.Role.AdminRole;
import Business.Role.DonorRole;
import Business.Role.ReceiverRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.SystemAdminWorkArea.SystemAdminManageJPanel;
import userInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author dabho
 */
public class AddUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form adduserJPanel
     */


    private JPanel userProcessContainer;
    private Enterprise enterprise;
   
    public AddUserJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise=enterprise;
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameJLabel = new javax.swing.JLabel();
        helpspeopleJLabel = new javax.swing.JLabel();
        organisationJLabel = new javax.swing.JLabel();
        locationJLabel = new javax.swing.JLabel();
        passwordJLabel5 = new javax.swing.JLabel();
        estimateddeliveryJLabel6 = new javax.swing.JLabel();
        deliverytimeJTextField = new javax.swing.JTextField();
        organisationNameJTextField = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        oldpeopleJCheckBox = new javax.swing.JCheckBox();
        todlerJCheckBox = new javax.swing.JCheckBox();
        childerenJCheckBox = new javax.swing.JCheckBox();
        babiesJCheckBox = new javax.swing.JCheckBox();
        allJCheckBox = new javax.swing.JCheckBox();
        adultsJCheckBox = new javax.swing.JCheckBox();
        createJButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        locationJLabel1 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        locationJLabel2 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        locationJLabel3 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        locationJLabel4 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        passwordJPasswordField = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameJLabel.setText("Add User");
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        helpspeopleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        helpspeopleJLabel.setText("Helps People of Category :");
        add(helpspeopleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 190, 30));

        organisationJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        organisationJLabel.setText("Organisation Name :");
        add(organisationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, 30));

        locationJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel.setText("Address line 1 : ");
        add(locationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 30));

        passwordJLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordJLabel5.setText("Password :");
        add(passwordJLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 30));

        estimateddeliveryJLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estimateddeliveryJLabel6.setText("Estimated Delivery Time :");
        add(estimateddeliveryJLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, 30));

        deliverytimeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverytimeJTextFieldActionPerformed(evt);
            }
        });
        add(deliverytimeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 220, -1));
        add(organisationNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 220, -1));
        add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 220, -1));

        oldpeopleJCheckBox.setText("Old People");
        add(oldpeopleJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 200, -1));

        todlerJCheckBox.setText("Todler");
        add(todlerJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 200, -1));

        childerenJCheckBox.setText("Children");
        add(childerenJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 200, -1));

        babiesJCheckBox.setText("Babies");
        add(babiesJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 200, -1));

        allJCheckBox.setText("All");
        add(allJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 200, -1));

        adultsJCheckBox.setText("Adults");
        adultsJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultsJCheckBoxActionPerformed(evt);
            }
        });
        add(adultsJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 200, -1));

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 120, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 120, 30));

        locationJLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel1.setText("Address line 2 :");
        add(locationJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 30));
        add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 220, -1));

        locationJLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel2.setText("City : ");
        add(locationJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 30));
        add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 220, -1));

        locationJLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel3.setText("State : ");
        add(locationJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 30));

        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 220, -1));

        locationJLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        locationJLabel4.setText("Country : ");
        add(locationJLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, 30));
        add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 220, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Username :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 220, -1));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void adultsJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultsJCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adultsJCheckBoxActionPerformed

    private void deliverytimeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverytimeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliverytimeJTextFieldActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        
        String userName = userNameJTextField.getText();
        String receiverName = organisationNameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String location= a1.getText()+", "+a2.getText()+", "+city.getText()+", "+state.getText()+", "+country.getText();
        String del=deliverytimeJTextField.getText();
        int delivery= Integer.parseInt(del);
        if(receiverName.matches("[a-zA-Z]+") && del.matches("[0-9]+")
                && userName.matches("[a-zA-Z]+"))
                {
        Organization org=null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
             if (organization instanceof ReceiverOrganization){
                org = organization;
                break;
            }
        }
        if(receiverName.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter Receiver name","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        Receiver r = org.getEmployeeDirectory().createReceiver(receiverName.trim());
        int i=0;
        String[] caters= new String[5];
        if(allJCheckBox.isSelected())
        {
            caters[0]=allJCheckBox.getText();
            
        }
        else
        {
        if(babiesJCheckBox.isSelected())
        {
            caters[i]=babiesJCheckBox.getText();
            i++;
            
        }
        if(todlerJCheckBox.isSelected())
        {
            caters[i]=todlerJCheckBox.getText();
            i++;
            
        }
        if(childerenJCheckBox.isSelected())
        {
            caters[i]=childerenJCheckBox.getText();
            i++;
            
        }
        if(adultsJCheckBox.isSelected())
        {
            caters[i]=adultsJCheckBox.getText();
            i++;
            
        }
        if(oldpeopleJCheckBox.isSelected())
        {
            caters[i]=oldpeopleJCheckBox.getText();
            i++;
            
        }
        }
        
        r.setCatersTo(caters);
        r.setDeliveryTime(delivery);
        r.setLocation(location);
        
        if(i==0)
        {
            JOptionPane.showMessageDialog(null, "Default category all selected", "Information", JOptionPane.INFORMATION_MESSAGE);

        }
        
        
        org.getUserAccountDirectory().createReceiverAccount(userName, password, r, new ReceiverRole());
        JOptionPane.showMessageDialog(null,"Receiver Created","Success",1);
                }
        else {
            JOptionPane.showMessageDialog(null, "Error in adding Receiver", "Information", JOptionPane.INFORMATION_MESSAGE);

        }
        


        
        /*
        String name = stateTextField.getText();

        Network network = system.createAndAddNetwork();
        network.setName(name);

        Enterprise.EnterpriseType type = Enterprise.EnterpriseType.Receiver;
        

        String enterpriseName = organisationNameJTextField.getText();

        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(enterpriseName, type);
        

        String username = userNameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        

        Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);

        
        UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new ReceiverRole());
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sawajp = (SystemAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

*/
    }//GEN-LAST:event_createJButtonActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JCheckBox adultsJCheckBox;
    private javax.swing.JCheckBox allJCheckBox;
    private javax.swing.JCheckBox babiesJCheckBox;
    private javax.swing.JCheckBox childerenJCheckBox;
    private javax.swing.JTextField city;
    private javax.swing.JTextField country;
    private javax.swing.JButton createJButton;
    private javax.swing.JTextField deliverytimeJTextField;
    private javax.swing.JLabel estimateddeliveryJLabel6;
    private javax.swing.JLabel helpspeopleJLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel locationJLabel;
    private javax.swing.JLabel locationJLabel1;
    private javax.swing.JLabel locationJLabel2;
    private javax.swing.JLabel locationJLabel3;
    private javax.swing.JLabel locationJLabel4;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JCheckBox oldpeopleJCheckBox;
    private javax.swing.JLabel organisationJLabel;
    private javax.swing.JTextField organisationNameJTextField;
    private javax.swing.JLabel passwordJLabel5;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JTextField state;
    private javax.swing.JCheckBox todlerJCheckBox;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
